# 错误处理

## `try...catch`

- `try...catch`同步执行，内部异步函数丢出的错误不会被捕获


